### ISSUE TITLE
能不能给天选红包加个最大时间限制

### ISSUE THREAD

**Issue by Astlm** [catlair/btdocs#16]
![Screenshot_2024-01-29-04-57-42-401_bin mt plus canary](https://github.com/catlair/btdocs/assets/106404630/721dbf22-5213-4852-afdf-0145f1541b3e)
有段时间一直收不到推送 原来是因为扫不到直播间就一直卡在这了 从1点扫到快5点。。。

**Comment by catlair** [comment]
这里是文档仓库

**Comment by catlair** [comment]
🌹🌹🌹增加 `redPack.scanAreaTimes` 扫描分区循环次数。默认三次，超出次数就退出。

issue 记得提到代码仓库哦
> 这里是文档仓库

**Comment by Astlm** [comment]
> 🌹🌹🌹增加 `redPack.scanAreaTimes` 扫描分区循环次数。默认三次，超出次数就退出。
> 
> issue 记得提到代码仓库哦
> 
> > 这里是文档仓库

好的 下次会注意的
